### ISSUE TITLE
Graphene 3.0 Support

### ISSUE THREAD

**Issue by hiporox** [EverWinter23/graphene-gis#15]
I see that you are target Graphene 3.0 support by March of '22. What needs to be done to enable this support? Do you have a checklist?

**Comment by EverWinter23** [comment]
Hi @hiporox, one minor issue prevents the update to `graphene==3.0.0`. One single test case is failing. I'm looking into it.

**Comment by EverWinter23** [comment]
@hiporox Has been released to `pypi`. Install using `pip install graphene-gis==0.0.8b0`
