### ISSUE TITLE
Unable to update graphene to v3

### ISSUE THREAD

**Issue by jacobjove** [EverWinter23/graphene-gis#21]
I'm unable to update graphene to v3 with the current published version of graphene-gis (0.0.7):

```
Because graphene-gis (0.0.7) depends on graphene (>=2.1,<3)
 and no versions of graphene-gis match >0.0.7,<0.0.8, graphene-gis (>=0.0.7,<0.0.8) requires graphene (>=2.1,<3).
So, because app depends on both graphene (^3.0.0) and graphene-gis (^0.0.7), version solving failed.
```
^ error message from Poetry

**Comment by EverWinter23** [comment]
Hi @iacobfred, `graphene-gis==0.0.7` is a stable version which requires `graphene >=2.1, <3`. If you wish to use `graphene-gis` with `graphene^3.0.0`, please use `graphene==0.0.8b` which is a pre-release version.

More info [v0.0.8b](https://github.com/EverWinter23/graphene-gis/releases/tag/v0.0.8b). Available on [pypi](https://pypi.org/project/graphene-gis/#history).

I hope that fixes your issue :)

PS: I think it's time to release v.0.0.8. I will do it soon as the pre-release version seems stable.

**Comment by EverWinter23** [comment]
I have released the update. Install using `pip install graphene-gis==0.0.8` with `graphene` v3 support.
