### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rad-eric** [EverWinter23/graphene-gis#4]
i fully realize this may be my own environment, but I am not clear of the issue - while trying the pip install, i get the following verbose error (attached)
given this line 
```
ld: library not found for -lssl
```
i assumed this was some kind of XCode dependency - even after an update i have not love
 I am working from a virtual environment...perhaps that is missing something?
[installerror.txt](https://github.com/EverWinter23/graphene-gis/files/5506587/installerror.txt)

**Comment by EverWinter23** [comment]
Sorry for replying late. `graphene-gis` requires `psycopg2` which is the postgres sql driver. Have you installed that?

**Comment by EverWinter23** [comment]
Closing, more info needed.

**Comment by kevindice** [comment]
I've got this same issue.  I'm installing `psycopg2-binary` but this package requiring `psycopg2` is breaking my build.

**Comment by kevindice** [comment]
Looks like the actual error is the lack of pg_conf existing.  The build of psycopg requires postgres to be installed because it has pg_conf.

If we can do an OR constraint on psycopg2 or psycopg2-binary, that would solve the issue.

**Comment by EverWinter23** [comment]
@kevindice Thanks for this information. Looking into it. Will try to patch is ASAP now that we do know the underlying cause.

**Update 1**: Proposed solution-- https://github.com/EverWinter23/graphene-gis/pull/5 LGTM

**Update 2**: Fixed and released on [pypi](https://pypi.org/project/graphene-gis/) -- `v0.0.6`
